version: '3.8'

services:
  jenkins:
    build:
      context: .
    container_name: jenkins-ssh
    ports:
      - "8080:8080"  # Jenkins Web UI
      - "2222:22"    # SSH access for Jenkins CLI
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/jenkins
      - DATABASE_USERNAME=jenkins
      - DATABASE_PASSWORD=jenkins_password
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: jenkins-db
    environment:
      - POSTGRES_USER=jenkins
      - POSTGRES_PASSWORD=jenkins_password
      - POSTGRES_DB=jenkins
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  jenkins_home:
  db_data:
